spring.application.name=sneaker-drops-7

spring.datasource.url=jdbc:mysql://localhost:3306/sneakerdrops
spring.datasource.username=root
spring.datasource.password=yearup26
spring.jps.show-sql=true

spring.jpa.hibernate.ddl-auto=update